fix(plc4go/modbus): Delete elements in the loop, and the index is dec…
apache/plc4x pull request #1028
Opened 2023-07-11 10:00 UTC by hongjinlin

In some batch read/write cases, because the element is deleted in the loop, but the index is not decremented by 1, the program freezes, and even the timeout does not work.

2023-07-12 08:31 UTC, sruehl requested changes
Please add a unit test for this change. It is such a central change which needs a test to proof the failure before the change and that it is working right after the change. The test then I can try out on the current develop to understand what exactly is happening

2023-07-12 08:32 UTC, sruehl commented
Small note: you can add a testcase in `DefaultCodec_test.go` before line 686

2023-07-12 08:35 UTC, sruehl commented
And looking at it: And easy fix would be to break the loop after we wound someone who accepted the message. There should be only one at a time accepting the message I think

2023-07-12 08:57 UTC, sruehl approved these changes
I could replicate the problem and verify that your fix fixes it. Thanks for the PR 🎉

2023-07-12 08:59 UTC, merged

2023-07-14 01:39 UTC, hongjinlin commented
> I could replicate the problem and verify that your fix fixes it. Thanks for the PR 🎉

Thanks for reviewing and adding testcase :sunglasses: .